[build]
builder = "NIXPACKS"
buildCommand = "npm install --ignore-scripts && npm run build"

[deploy]
startCommand = "npx prisma generate && npx prisma migrate deploy && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
